DEFAULT_CHATTERBOX_STATUS_MESSAGE = (
    'Chatterbox is available as an optional download.'
)

CHATTERBOX_REFERENCE_CACHE_VERSION = 'chatterbox_ref_v1'
CHATTERBOX_COND_CACHE_VERSION = 'chatterbox_cond_v1'
CHATTERBOX_SAMPLE_RATE_FALLBACK = 24000
CHATTERBOX_SILENCE_THRESHOLD = 0.0042
CHATTERBOX_SILENCE_PAD_MS = 92
CHATTERBOX_STUDIO_SILENCE_THRESHOLD = 0.0031
CHATTERBOX_STUDIO_SILENCE_PAD_MS = 132
CHATTERBOX_MEMORY_COND_CACHE_LIMIT = 8
CHATTERBOX_APPLY_WATERMARK = False

PREPAREABLE_ENGINES = {'chatterbox', 'xtts'}
CHATTERBOX_ENGINE_ALIASES = {'chatterbox', 'xtts'}
